In [ ]:
pip install pgmpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pgmpy
  Downloading pgmpy-0.1.20-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 4.4 MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pgmpy) (1.21.6)
Requirement already satisfied: networkx in /usr/local/lib/python3.7/dist-packages (from pgmpy) (2.6.3)
Requirement already satisfied: torch in /usr/local/lib/python3.7/dist-packages (from pgmpy) (1.12.1+cu113)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from pgmpy) (1.7.3)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.7/dist-packages (from pgmpy) (3.3.0)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.7/dist-packages (from pgmpy) (0.12.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from pgmpy) (1.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pgmpy) (1.3.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from pgmpy) (4.64.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from pgmpy) (1.2.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.7/dist-packages (from pgmpy) (3.0.9)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pgmpy) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pgmpy) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pgmpy) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->pgmpy) (3.1.0)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.7/dist-packages (from statsmodels->pgmpy) (0.5.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch->pgmpy) (4.1.1)
Installing collected packages: pgmpy
Successfully installed pgmpy-0.1.20

In [ ]:
import numpy as np
import pandas as pd
import csv
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.models import BayesianModel
from pgmpy.inference import VariableElimination

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Google Colab/Datasets/heart.csv")
df

     age  gender  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  heartdisease
0     63       1   1       145   233  ...      2.3      3   0     6             0
1     67       1   4       160   286  ...      1.5      2   3     3             2
2     67       1   4       120   229  ...      2.6      2   2     7             1
3     37       1   3       130   250  ...      3.5      3   0     3             0
4     41       0   2       130   204  ...      1.4      1   0     3             0
..   ...     ...  ..       ...   ...  ...      ...    ...  ..   ...           ...
298   45       1   1       110   264  ...      1.2      2   0     7             1
299   68       1   4       144   193  ...      3.4      2   2     7             2
300   57       1   4       130   131  ...      1.2      2   1     7             3
301   57       0   2       130   236  ...      0.0      2   1     3             1
302   38       1   3       138   175  ...      0.0      1   ?     3             0

[303 rows x 14 columns]

In [ ]:
df=df.replace('?',np.nan)
print("Sample instance from heart dataset are given below")
print(df.head())

print("\n Attributes and Datatypes")
print(df.dtypes)

model = BayesianModel([("age","heartdisease"),("gender","heartdisease"),("exang","heartdisease"),("cp","heartdisease"),("heartdisease","restecg"),("heartdisease","chol")])
print("\nLearning CPD using MAximum Likelihood Estimators")
model.fit(df,estimator=MaximumLikelihoodEstimator)

print("\n Inferencing with Bayesian Network:")
HeartDiseasetest_infer = VariableElimination(model)

print("\n 1.Probability of HeartDisease given evidence = restecg")
q1=HeartDiseasetest_infer.query(variables=['heartdisease'],evidence={'restecg':1})
print(q1)

print("\n 1.Probability of HeartDisease given evidence = cp")
q2=HeartDiseasetest_infer.query(variables=['heartdisease'],evidence={'cp':2})
print(q2)

Sample instance from heart dataset are given below
   age  gender  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  heartdisease
0   63       1   1       145   233  ...      2.3      3   0     6             0
1   67       1   4       160   286  ...      1.5      2   3     3             2
2   67       1   4       120   229  ...      2.6      2   2     7             1
3   37       1   3       130   250  ...      3.5      3   0     3             0
4   41       0   2       130   204  ...      1.4      1   0     3             0

[5 rows x 14 columns]

 Attributes and Datatypes
age               int64
gender            int64
cp                int64
trestbps          int64
chol              int64
fbs               int64
restecg           int64
thalach           int64
exang             int64
oldpeak         float64
slope             int64
ca               object
thal             object
heartdisease      int64
dtype: object

Learning CPD using MAximum Likelihood Estimators

 Inferencing with Bayesian Network:

 1.Probability of HeartDisease given evidence = restecg
+-----------------+---------------------+
| heartdisease    |   phi(heartdisease) |
+=================+=====================+
| heartdisease(0) |              0.1012 |
+-----------------+---------------------+
| heartdisease(1) |              0.0000 |
+-----------------+---------------------+
| heartdisease(2) |              0.2392 |
+-----------------+---------------------+
| heartdisease(3) |              0.2015 |
+-----------------+---------------------+
| heartdisease(4) |              0.4581 |
+-----------------+---------------------+

 1.Probability of HeartDisease given evidence = cp
+-----------------+---------------------+
| heartdisease    |   phi(heartdisease) |
+=================+=====================+
| heartdisease(0) |              0.3610 |
+-----------------+---------------------+
| heartdisease(1) |              0.2159 |
+-----------------+---------------------+
| heartdisease(2) |              0.1373 |
+-----------------+---------------------+
| heartdisease(3) |              0.1537 |
+-----------------+---------------------+
| heartdisease(4) |              0.1321 |
+-----------------+---------------------+

/usr/local/lib/python3.7/dist-packages/pgmpy/models/BayesianModel.py:10: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  FutureWarning,